### ISSUE TITLE
SequenceReader does not reset sequence when reading fasta

### ISSUE THREAD

**Issue by sgblanch** [raw-lab/DeGenPrime#11]
SequenceReader::CreateList() does not correctly clear its residues between sequences when reading FASTA.  Instead, it keeps appending the residues. In what is stored in the returned`SequenceList` is effectively:

```
seq1 = seq1
seq2 = seq1 + seq2
seqN = seq1 + seq2 + ... + seqN
```

**Comment by zestywesty** [comment]
Into the Sequence.h and Sequence.cpp files, I added a Clear() function which clears the data on the sequence.
Into the SequenceReader.cpp CreateList function, I added a call to this function in the fasta while loop
