### ISSUE TITLE
DeGenPrime will go into endless loop if supplied clust is empty

### ISSUE THREAD

**Issue by sgblanch** [raw-lab/DeGenPrime#6]
If degenprime is run on an empty clust file, degenprime will enter an endless loop

```console
$ touch empty.clust
$ degenprime empty.clust
```

**Comment by sgblanch** [comment]
Finally got debugger working.  Loops in `SequenceReader::FindEndOfHeader()` do not check for `EOF`.

**Comment by zestywesty** [comment]
I added a few statements to sequencereader.cpp

First, in the FindEndOfHeader function:
if(ifs.peek() == std::ifstream::traits_type::eof())
{
	return;
}
This stops the infinite loop.

Next, just after the while loop nested in the switch block of the CreateList function,
if(list.size() == 0)
{
    cout << "Error. " << GlobalSettings::GetInputFile() << " contained no sequences." << endl;
    exit(BAD_INPUT_FILE);
}

This stops program operation in the case someone enters an empty file.
