### ISSUE TITLE
Return value for system() calls is not checked

### ISSUE THREAD

**Issue by sgblanch** [raw-lab/DeGenPrime#7]
Currently `system()` calls are surrounded by `try-catch` blocks but `system()` does not throw exceptions.  Instead, the return value of `system()` calls need to be checked for errors. 

Failure to check the return value of the `mafft` call can cause #6 if the `mafft` call fails.

**Comment by zestywesty** [comment]
DeGenPrime no longer uses recursive calls to align sequences for the user.  The user will have to manually align their sequences using mafft or other software.  We present a warning for unaligned files and end the program.
