### ISSUE TITLE
Allow user to specify output file name

### ISSUE THREAD

**Issue by sgblanch** [raw-lab/DeGenPrime#8]
Currently the output file name is based on the input file name.  It would be nice to allow the user to specify the output file name.  For example, this would be important when running degenprime with different options on the same file concurrently--on a cluster for example.

**Comment by zestywesty** [comment]
Degenprime now includes the following tags:
--input_file:<filename>
--output_file:<filename>

the --input_file tag is now required for any program feature outside of the --help and --test tags.
the --output_file tag is not required.  If it is entered, the program will write a csv to the specified filename.  if it is not specified, the program will use the input_file name up to the file extension, which will be replaced with .csv

**Comment by zestywesty** [comment]
Closed 9 March 2024
